image: maven:3.6-jdk-8
pipelines:
    default:
        - step:
            name: Compile & test
            caches:
                - maven
            script:
                - mvn -version
                - bash configure-maven.sh
                - mvn clean install
        - step:
            name: Release
            trigger: manual
            caches:
                - maven
            script:
                - bash configure-maven.sh
                - git config --global user.email "$email"
                - git config --global user.name "$name"
                - mvn versions:set -DremoveSnapshot=true versions:resolve-ranges
                - mvn clean deploy
                - version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
                - git commit -n -a -m "[skip ci] Release of $version"
                - git tag -a -m "Release of $version" RELEASE-$version
                - git push origin RELEASE-$version
                - mvn versions:revert
                - mvn versions:set -DnextSnapshot=true
                - git commit -a -n -m "Next version"
                - git push
