apiVersion: v1
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: personify
    creationTimestamp: null
    labels:
      app: personify-scim-server
    name: personify-scim-server
  spec:
    replicas: 1
    selector:
      app: personify-scim-server
      deploymentconfig: personify-scim-server
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: personify
        creationTimestamp: null
        labels:
          app: personify-scim-server
          deploymentconfig: personify-scim-server
      spec:
        containers:
        - image: 172.30.1.1:5000/personify/personify-scim-server:1.5.8.RELEASE
          name: personify-scim-server
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          volumeMounts:
          - mountPath: /tmp
            name: personify-scim-server-volume-1
        volumes:
        - emptyDir: {}
          name: personify-scim-server-volume-1
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - personify-scim-server
        from:
          kind: ImageStreamTag
          name: personify-scim-server:1.5.8.RELEASE
          namespace: personify
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: personify
    creationTimestamp: null
    labels:
      app: personify-scim-server
    name: personify-scim-server
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: personify-scim-server
      deploymentconfig: personify-scim-server
  status:
    loadBalancer: {}
kind: List
metadata: {}
